import Head from 'next/head'
import styles from './index.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div className={styles.test}>
        <button className={styles.test1}>Click Me</button>
      </div>
      <div className="d-flex justify-content-center">
        <button className="btn btn-primary text-center">Click Me</button>
      </div>
    </div>
  )
}
